apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - urlshortener-deployment.yaml
  - urlshortener-service.yaml
  - urlshortener-ingress.yaml
  - mssql-deployment.yaml
  - mssql-service.yaml
  - mssql-pvc.yaml
  - mssql-secret.yaml 