apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'YourStrongPassword123!' | base64
  sa-password: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==
  connection-string: U2VydmVyPW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9VVJMU2hvcnRlbmVyRGI7VXNlciBJZD1zYTtQYXNzd29yZD1Zb3VyU3Ryb25nUGFzc3dvcmQxMjMhO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs= 